/**
 * Seed script to initialize Computer Science syllabus with categorized topics
 * Run this once to populate the database with the complete syllabus
 */

import { storeGlobalSyllabus, TopicCategory } from "./aihub";

export const COMPUTER_SCIENCE_SYLLABUS: TopicCategory[] = [
  {
    name: "Digital Logic and Circuits",
    description: "Computer Science fundamentals",
    subtopics: [
      "Number Systems",
      "Boolean Algebra",
      "Logic Gates",
      "Simplification of Boolean Functions",
      "Combinational Circuits",
      "Sequential Circuits",
      "Memory Circuits",
    ],
  },
  {
    name: "Discrete Mathematical Structures",
    description: "Mathematical foundations for CS",
    subtopics: [
      "Sets and Set Operations",
      "Relations and Functions",
      "Mathematical Logic",
      "Boolean Algebra",
      "Combinatorics",
      "Recurrence Relations",
      "Graph Theory",
    ],
  },
  {
    name: "Computer Organization and Architecture",
    description: "CPU and system organization",
    subtopics: [
      "Stored Program Concept",
      "Components of a Computer System",
      "Machine Instruction",
      "Op codes and Operands",
      "Instruction Cycle",
      "Central Processing Unit (CPU) Organization",
      "Arithmetic Logic Unit (ALU)",
      "Hardwired Control Unit",
      "Micro-programmed Control Unit",
      "General Purpose Registers",
      "Special Purpose Registers",
      "Memory Organization",
      "I/O Organization",
      "CPU Functioning",
      "Instruction Formats",
      "Instruction Types",
      "Addressing Modes",
      "Common Microprocessor Instructions",
      "Multi-core Architecture",
      "Multiprocessor Systems",
      "Multicomputer Systems",
    ],
  },
  {
    name: "Data Structures and Algorithm",
    description: "Data organization and algorithm design",
    subtopics: [
      "Definition and Types of Data Structures",
      "Linear Structures",
      "Non-Linear Data Structures",
      "Hashing and Collision Resolution",
      "Searching Algorithms",
      "Sorting Algorithms",
      "Algorithm Analysis",
      "Complexity of Algorithms",
      "Growth of Functions",
      "Performance Measurements",
      "Red-Black Trees",
      "B-Trees",
      "Binomial Heaps",
      "Fibonacci Heaps",
      "Divide and Conquer",
      "Greedy Algorithms",
      "Optimal Reliability Allocation",
      "Knapsack Problem",
      "Minimum Spanning Trees",
      "Prim's Algorithm",
      "Kruskal's Algorithm",
      "Single Source Shortest Paths",
      "Dijkstra's Algorithm",
      "Bellman Ford Algorithm",
      "Dynamic Programming",
      "All Pair Shortest Paths",
      "Warshal's Algorithm",
      "Floyd's Algorithm",
      "Resource Allocation",
      "Backtracking",
      "Branch and Bound",
      "Travelling Salesman Problem",
      "Graph Coloring",
      "n-Queen Problem",
      "Hamiltonian Cycles",
      "Sum of Subsets",
      "Algebraic Computation",
      "Fast Fourier Transform",
      "String Matching",
      "Theory of NP-Completeness",
      "Approximation Algorithms",
      "Randomized Algorithms",
    ],
  },
  {
    name: "Problem Solving through C Programming",
    description: "C programming language fundamentals",
    subtopics: [
      "Basic Programming Concepts",
      "Introduction to C Language",
      "Variables and Data Types",
      "Control Flow Statements",
      "Functions",
      "Arrays and Strings",
      "Pointers",
      "Structures and Unions",
      "File Handling",
      "Memory Management",
    ],
  },
  {
    name: "Object Oriented Techniques",
    description: "OOP concepts and design patterns",
    subtopics: [
      "Object Orientation",
      "Encapsulation",
      "Information Hiding",
      "Polymorphism",
      "Inheritance",
      "Object Oriented Modeling",
      "Unified Modeling Language (UML)",
      "Structural Modeling",
      "Behavioral Modeling",
      "Architectural Modeling",
      "Object Oriented Analysis",
      "Object Oriented Design",
      "Structured Analysis and Design (SA/SD)",
      "Jackson Structured Development (JSD)",
      "Introduction to Java",
      "Java Beans",
      "Enterprise Java Beans (EJB)",
      "Java Swing",
      "Java as Internet Programming Language",
      "Connectivity Model",
      "JDBC/ODBC",
      "Bridge Pattern",
      "Introduction to Servlets",
    ],
  },
  {
    name: "Operating System",
    description: "OS concepts and management",
    subtopics: [
      "Definition of Operating System",
      "Design Goals",
      "Evolution of OS",
      "Structure and Functions",
      "Process Management",
      "Memory Management",
      "Concurrent Processes",
      "File Management",
      "Secondary Storage Management",
      "UNIX Operating System",
      "Shell Programming",
      "Windows Programming",
    ],
  },
  {
    name: "Database Management Systems",
    description: "Database design and management",
    subtopics: [
      "Database Systems Overview",
      "View of Data Models",
      "Database Languages",
      "DBMS Architecture",
      "Database Users",
      "Data Independence",
      "Entity-Relationship (ER) Modeling",
      "Relational Model",
      "Introduction to SQL",
      "Relational Database Design",
      "Database Normalization",
      "Database Security",
      "Transaction Management",
      "ACID Properties",
      "Query Processing",
      "Query Optimization",
      "Concurrency Control",
      "Recovery Techniques",
      "Deadlock Management",
    ],
  },
  {
    name: "Computer Networks",
    description: "Network architecture and protocols",
    subtopics: [
      "Network Definition",
      "Network Topologies",
      "Network Classifications",
      "Network Protocol",
      "Layered Network Architecture",
      "OSI Reference Model",
      "TCP/IP Protocol Suite",
      "Data Communication Fundamentals",
      "Data Communication Techniques",
      "Network Switching Techniques",
      "Access Mechanisms",
      "Data Link Layer Functions",
      "Data Link Layer Protocols",
      "Multiple Access Protocols",
      "Network Layer Functions",
      "Network Layer Protocols",
      "Transport Layer Functions",
      "Transport Layer Protocols",
      "Application Layer Protocols",
    ],
  },
  {
    name: "Software Engineering",
    description: "Software development and quality",
    subtopics: [
      "Software Definition",
      "Software Development",
      "Software Life-Cycle Models",
      "Capability Maturity Model (CMM)",
      "Software Quality",
      "Metrics and Measurement",
      "Requirements Analysis",
      "Requirements Specification",
      "Software Project Planning",
      "Software Architecture",
      "Software Design",
      "Software Implementation",
      "Software Testing",
      "Software Reliability",
    ],
  },
  {
    name: "Internet Technology and Web Design",
    description: "Web development and protocols",
    subtopics: [
      "Internet Technology",
      "Internet Protocols",
      "Internet Architecture",
      "Internet Networks",
      "Services on Internet",
      "Electronic Mail",
      "Current Trends on Internet",
      "Web Publishing",
      "Web Browsing",
      "HTML Programming Basics",
      "Interactivity Tools",
      "Web Design Principles",
      "Web Development Strategies",
      "Web Applications",
      "Web Page Designing",
      "Scripting",
      "Server-Side Programming",
      "Web Protocols",
    ],
  },
  {
    name: "System Analysis and Design",
    description: "Information systems development",
    subtopics: [
      "Analysis and Design of a System",
      "Documenting Systems",
      "Evaluating Systems",
      "Data Modeling",
      "Development of Information Management System",
      "Implementation",
      "Testing",
      "Security Aspects",
    ],
  },
  {
    name: "Information Security and Cyber Laws",
    description: "Security and cybercrime",
    subtopics: [
      "Distributed Information Systems",
      "Role of Internet and Web Services",
      "Threats and Attacks",
      "Assessing Damages",
      "Security in Mobile Computing",
      "Security in Wireless Computing",
      "Security Threats to E-Commerce",
      "E-Governance",
      "Electronic Data Interchange (EDI)",
      "Electronics Payment Systems",
      "E-Cash",
      "Credit Cards",
      "Debit Cards",
      "Physical Security Needs",
      "Disaster and Controls",
      "Physical Security Basics",
      "Physical Entry Controls",
      "Access Control",
      "Cryptographic Systems",
      "Cryptographic Design",
      "Cryptographic Implementation",
      "Security Policies",
      "Network Security",
      "Network Attacks",
      "Intrusion Monitoring",
      "Intrusion Detection",
      "Security Metrics",
      "Information Security",
      "Cyber Laws",
      "Ethics",
      "Data Privacy",
      "Software Privacy",
      "Cyber Crimes",
      "Ethical Issues",
    ],
  },
  {
    name: "Computer Graphics",
    description: "Graphics and visualization",
    subtopics: [
      "Types of Computer Graphics",
      "Graphic Displays",
      "Random Scan Displays",
      "Raster Scan Displays",
      "Frame Buffer",
      "Video Controller",
      "Line Generating Algorithms",
      "Circle Generating Algorithms",
      "Transformations",
      "Windowing",
      "Clipping",
      "Three Dimensional Graphics",
      "Curves and Surfaces",
      "Hidden Lines",
      "Hidden Surfaces",
    ],
  },
];

/**
 * Initialize the global syllabus in MongoDB
 */
export async function initializeSyllabus() {
  try {
    await storeGlobalSyllabus("Computer Science", COMPUTER_SCIENCE_SYLLABUS);
  } catch (error) {
    console.error("[Syllabus] Failed to initialize:", error instanceof Error ? error.message : "Unknown error");
    throw error;
  }
}
