/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AppTestsRouteImport } from './routes/_app/tests'
import { Route as AppSyllabusRouteImport } from './routes/_app/syllabus'
import { Route as AppSubmissionsRouteImport } from './routes/_app/submissions'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNoticesRouteImport } from './routes/_app/notices'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAihubRouteImport } from './routes/_app/aihub'
import { Route as AppTestsTestIdRouteImport } from './routes/_app/tests.$testId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminTestsRouteImport } from './routes/_app/admin.tests'
import { Route as AppAdminSubmissionsRouteImport } from './routes/_app/admin.submissions'
import { Route as AppAdminNoticesRouteImport } from './routes/_app/admin.notices'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin.dashboard'
import { Route as AppAdminTestsTestIdRouteImport } from './routes/_app/admin/tests.$testId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppSyllabusRoute = AppSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAihubRoute = AppAihubRouteImport.update({
  id: '/aihub',
  path: '/aihub',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppTestsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTestsRoute = AppAdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSubmissionsRoute = AppAdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNoticesRoute = AppAdminNoticesRouteImport.update({
  id: '/admin/notices',
  path: '/admin/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTestsTestIdRoute = AppAdminTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppAdminTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/aihub': typeof AppAihubRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notices': typeof AppNoticesRoute
  '/profile': typeof AppProfileRoute
  '/submissions': typeof AppSubmissionsRoute
  '/syllabus': typeof AppSyllabusRoute
  '/tests': typeof AppTestsRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/notices': typeof AppAdminNoticesRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/tests': typeof AppAdminTestsRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/tests/$testId': typeof AppTestsTestIdRoute
  '/admin/tests/$testId': typeof AppAdminTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/aihub': typeof AppAihubRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notices': typeof AppNoticesRoute
  '/profile': typeof AppProfileRoute
  '/submissions': typeof AppSubmissionsRoute
  '/syllabus': typeof AppSyllabusRoute
  '/tests': typeof AppTestsRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/notices': typeof AppAdminNoticesRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/tests': typeof AppAdminTestsRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/tests/$testId': typeof AppTestsTestIdRoute
  '/admin/tests/$testId': typeof AppAdminTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/_app/aihub': typeof AppAihubRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/submissions': typeof AppSubmissionsRoute
  '/_app/syllabus': typeof AppSyllabusRoute
  '/_app/tests': typeof AppTestsRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/notices': typeof AppAdminNoticesRoute
  '/_app/admin/submissions': typeof AppAdminSubmissionsRoute
  '/_app/admin/tests': typeof AppAdminTestsRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/tests/$testId': typeof AppTestsTestIdRoute
  '/_app/admin/tests/$testId': typeof AppAdminTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/login'
    | '/aihub'
    | '/dashboard'
    | '/leaderboard'
    | '/notices'
    | '/profile'
    | '/submissions'
    | '/syllabus'
    | '/tests'
    | '/api/ping'
    | '/admin/dashboard'
    | '/admin/notices'
    | '/admin/submissions'
    | '/admin/tests'
    | '/admin/users'
    | '/tests/$testId'
    | '/admin/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/aihub'
    | '/dashboard'
    | '/leaderboard'
    | '/notices'
    | '/profile'
    | '/submissions'
    | '/syllabus'
    | '/tests'
    | '/api/ping'
    | '/admin/dashboard'
    | '/admin/notices'
    | '/admin/submissions'
    | '/admin/tests'
    | '/admin/users'
    | '/tests/$testId'
    | '/admin/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin-login'
    | '/login'
    | '/_app/aihub'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/notices'
    | '/_app/profile'
    | '/_app/submissions'
    | '/_app/syllabus'
    | '/_app/tests'
    | '/api/ping'
    | '/_app/admin/dashboard'
    | '/_app/admin/notices'
    | '/_app/admin/submissions'
    | '/_app/admin/tests'
    | '/_app/admin/users'
    | '/_app/tests/$testId'
    | '/_app/admin/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LoginRoute: typeof LoginRoute
  ApiPingRoute: typeof ApiPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/syllabus': {
      id: '/_app/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AppSyllabusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submissions': {
      id: '/_app/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aihub': {
      id: '/_app/aihub'
      path: '/aihub'
      fullPath: '/aihub'
      preLoaderRoute: typeof AppAihubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests/$testId': {
      id: '/_app/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppTestsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tests': {
      id: '/_app/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AppAdminTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/submissions': {
      id: '/_app/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AppAdminSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notices': {
      id: '/_app/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AppAdminNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tests/$testId': {
      id: '/_app/admin/tests/$testId'
      path: '/$testId'
      fullPath: '/admin/tests/$testId'
      preLoaderRoute: typeof AppAdminTestsTestIdRouteImport
      parentRoute: typeof AppAdminTestsRoute
    }
  }
}

interface AppTestsRouteChildren {
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
}

const AppTestsRouteChildren: AppTestsRouteChildren = {
  AppTestsTestIdRoute: AppTestsTestIdRoute,
}

const AppTestsRouteWithChildren = AppTestsRoute._addFileChildren(
  AppTestsRouteChildren,
)

interface AppAdminTestsRouteChildren {
  AppAdminTestsTestIdRoute: typeof AppAdminTestsTestIdRoute
}

const AppAdminTestsRouteChildren: AppAdminTestsRouteChildren = {
  AppAdminTestsTestIdRoute: AppAdminTestsTestIdRoute,
}

const AppAdminTestsRouteWithChildren = AppAdminTestsRoute._addFileChildren(
  AppAdminTestsRouteChildren,
)

interface AppRouteChildren {
  AppAihubRoute: typeof AppAihubRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppSyllabusRoute: typeof AppSyllabusRoute
  AppTestsRoute: typeof AppTestsRouteWithChildren
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminNoticesRoute: typeof AppAdminNoticesRoute
  AppAdminSubmissionsRoute: typeof AppAdminSubmissionsRoute
  AppAdminTestsRoute: typeof AppAdminTestsRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAihubRoute: AppAihubRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppSyllabusRoute: AppSyllabusRoute,
  AppTestsRoute: AppTestsRouteWithChildren,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminNoticesRoute: AppAdminNoticesRoute,
  AppAdminSubmissionsRoute: AppAdminSubmissionsRoute,
  AppAdminTestsRoute: AppAdminTestsRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LoginRoute: LoginRoute,
  ApiPingRoute: ApiPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
