/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTestsRouteImport } from './routes/_app/tests'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTestsTestIdRouteImport } from './routes/_app/tests.$testId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminTestsRouteImport } from './routes/_app/admin.tests'
import { Route as AppAdminSubmissionsRouteImport } from './routes/_app/admin.submissions'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppTestsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTestsRoute = AppAdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSubmissionsRoute = AppAdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/tests': typeof AppTestsRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/tests': typeof AppAdminTestsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tests/$testId': typeof AppTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/tests': typeof AppTestsRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/submissions': typeof AppAdminSubmissionsRoute
  '/admin/tests': typeof AppAdminTestsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tests/$testId': typeof AppTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tests': typeof AppTestsRouteWithChildren
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/submissions': typeof AppAdminSubmissionsRoute
  '/_app/admin/tests': typeof AppAdminTestsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/tests/$testId': typeof AppTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/login'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/tests'
    | '/admin/dashboard'
    | '/admin/submissions'
    | '/admin/tests'
    | '/admin/users'
    | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/tests'
    | '/admin/dashboard'
    | '/admin/submissions'
    | '/admin/tests'
    | '/admin/users'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin-login'
    | '/login'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/profile'
    | '/_app/tests'
    | '/_app/admin/dashboard'
    | '/_app/admin/submissions'
    | '/_app/admin/tests'
    | '/_app/admin/users'
    | '/_app/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests/$testId': {
      id: '/_app/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppTestsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tests': {
      id: '/_app/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AppAdminTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/submissions': {
      id: '/_app/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AppAdminSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTestsRouteChildren {
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
}

const AppTestsRouteChildren: AppTestsRouteChildren = {
  AppTestsTestIdRoute: AppTestsTestIdRoute,
}

const AppTestsRouteWithChildren = AppTestsRoute._addFileChildren(
  AppTestsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTestsRoute: typeof AppTestsRouteWithChildren
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminSubmissionsRoute: typeof AppAdminSubmissionsRoute
  AppAdminTestsRoute: typeof AppAdminTestsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppTestsRoute: AppTestsRouteWithChildren,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminSubmissionsRoute: AppAdminSubmissionsRoute,
  AppAdminTestsRoute: AppAdminTestsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
